import os
import subprocess
import json
import google.generativeai as genai

def generate_metadata(story_plan_path):
    """
    Uses Gemini to generate a catchy YouTube title and description based on the story plan.
    """
    if not os.path.exists(story_plan_path):
        return "Untitled Vlog", "Generated by AI Director."

    with open(story_plan_path, 'r') as f:
        plan_content = f.read()

    # Get model from settings if available
    base_dir = os.path.dirname(os.path.abspath(__file__))
    settings_file = os.path.join(base_dir, "backend", "settings.json")
    model_name = "models/gemini-1.5-flash"
    if os.path.exists(settings_file):
        try:
            with open(settings_file, "r") as f:
                settings = json.load(f)
                if "geminiModel" in settings:
                    model_name = settings["geminiModel"]
                    if not model_name.startswith("models/"):
                        model_name = f"models/{model_name}"
        except:
            pass

    model = genai.GenerativeModel(model_name=model_name)
    
    prompt = f"""
    Based on the following video cutting plan, generate:
    1. A catchy, clickable YouTube video title (under 100 characters).
    2. A compelling video description (3-4 paragraphs) that summarizes the story and includes a "Chapters" section with timestamps based on the scene titles and durations.
    
    Output the result as a raw JSON object with keys "title" and "description". Do NOT include markdown code blocks.
    
    Cutting Plan:
    {plan_content}
    """
    
    try:
        response = model.generate_content(prompt)
        # Clean up possible markdown wrapper if Gemini ignores instruction
        clean_text = response.text.strip()
        if clean_text.startswith("```json"):
            clean_text = clean_text.split("```json")[1].split("```")[0].strip()
        elif clean_text.startswith("```"):
            clean_text = clean_text.split("```")[1].split("```")[0].strip()
            
        data = json.loads(clean_text)
        return data.get("title", "Untitled Vlog"), data.get("description", "Generated by AI Director.")
    except Exception as e:
        print(f"Error generating metadata: {e}")
        return "AI Generated Vlog", f"A video generated from: {os.path.basename(story_plan_path)}"

def extract_thumbnail(video_path, output_path, timestamp=None):
    """
    Extracts a high-quality frame from the video at the specified timestamp or 10% in.
    """
    if timestamp is None:
        # Get duration and pick a point 10% in
        try:
            cmd = ['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'default=noprint_wrappers=1:nokey=1', video_path]
            duration = float(subprocess.check_output(cmd).decode().strip())
            timestamp = duration * 0.1
        except:
            timestamp = 2.0 # Fallback
            
    cmd = [
        'ffmpeg', '-ss', str(timestamp), '-i', video_path,
        '-vframes', '1', '-q:v', '2', '-y', output_path
    ]
    try:
        subprocess.run(cmd, check=True, capture_output=True)
        return True
    except subprocess.CalledProcessError as e:
        print(f"Error extracting thumbnail: {e.stderr.decode()}")
        return False

if __name__ == "__main__":
    # Test
    import sys
    if len(sys.argv) > 1:
        t, d = generate_metadata(sys.argv[1])
        print(f"TITLE: {t}\n\nDESCRIPTION:\n{d}")
